# fly.toml app configuration file generated for alpine-linux-smart-vpn on 2025-07-13T18:30:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alpine-linux-smart-vpn'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 22
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
